---

- name: Install VIM
  apt: pkg=vim state=present
  sudo: yes

- name: Install Git
  apt: pkg=git state=present
  sudo: yes

- name: Verify RCM installation
  stat: path={{ rcm_installation_path }}
  register: rcm_installed

- name: Install RCM
  sudo: yes
  shell: wget https://thoughtbot.github.io/rcm/debs/rcm_1.2.3-1_all.deb
         && dpkg -i rcm_1.2.3-1_all.deb
  when: rcm_installed.stat.exists == false

- name: Install tmux
  sudo: yes
  apt: name=tmux state=present update_cache=yes

- name: Validate Ack Installation
  shell: which ack
  register: ack_path
  ignore_errors: yes

- name: Install Ack
  sudo: yes
  shell: curl http://beyondgrep.com/ack-2.12-single-file > /usr/bin/ack && chmod 0755 /usr/bin/ack
  when: ack_path.rc != 0
